### ISSUE TITLE
Not able to compile with g++-7.1.1

### ISSUE THREAD

**Issue by invexed** [agenium-scale/boost.simd#540]
As the title states, g++-7.1.1 gives multiple compilation errors, the first of which are:

```
.../include/boost/simd/detail/dispatch/meta/model_of.hpp:52:31:

error: ambiguous template instantiation for ‘struct boost::dispatch::ext::model_of<boost::simd::pack<float>, void>’
   template<typename T> struct model_of                    : ext::model_of<T>  {};
                               ^~~~~~~~
```

```
.../include/boost/simd/detail/dispatch/meta/model_of.hpp:52:31:

error: invalid use of incomplete type ‘struct boost::dispatch::ext::model_of<boost::simd::pack<float>, void>’
   template<typename T> struct model_of                    : ext::model_of<T>  {};
                               ^~~~~~~~
```

**Comment by jfalcou** [comment]
Hi 

This is indeed something we reproduced. However we're currently revamping a massive amount of this code so I'm ot sure we'll have time to fix this before september release where this exact metafunction just disappear.

PS: I'll answer your mail a bit later with more infos.

**Comment by invexed** [comment]
A temporary workaround is to comment out the `Template<Type>` specialization in `.../boost/simd/detail/dispatch/detail/model_of.hpp`

**Comment by johnmcfarlane** [comment]
FWIW:
* also happens with GCC 7.1.0;
* doesn't seem to happen with Boost 1.60 (Travis-CI Ubuntu 14.04 default) but 
* does happen with Boost 1.62 (Debian Stretch)
* and only occurs in C++17 builds so passing `-DCXX_STD=14` to `cmake` works around the problem.
